
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ack-elasticache-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheparametergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheparametergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cachesubnetgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cachesubnetgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - replicationgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - replicationgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - snapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - usergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - usergroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
