---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-elasticache-reader
  namespace: default
rules:
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheparametergroups
  - cachesubnetgroups
  - replicationgroups
  - snapshots
  verbs:
  - get
  - list
  - watch
