---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-elasticache-writer
  namespace: default
rules:
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheparametergroups
  - cachesubnetgroups
  - replicationgroups
  - snapshots
  - users
  - usergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticache.services.k8s.aws
  resources:
  - cacheparametergroups
  - cachesubnetgroups
  - replicationgroups
  - snapshots
  - users
  - usergroups
  verbs:
  - get
  - patch
  - update
