apiVersion: v1
name: ack-apigatewayv2-controller
description: A Helm chart for the ACK service controller for apigatewayv2
version: v0.0.2
appVersion: v0.0.2
home: https://github.com/aws/aws-controllers-k8s
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws/aws-controllers-k8s
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws/teams/aws-controllers-for-kubernetes-ack-admins
keywords:
  - aws
  - kubernetes
  - apigatewayv2
