
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: tables.dynamodb.services.k8s.aws
spec:
  group: dynamodb.services.k8s.aws
  names:
    kind: Table
    listKind: TableList
    plural: tables
    singular: table
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Table is the Schema for the Tables API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TableSpec defines the desired state of Table
            properties:
              attributeDefinitions:
                items:
                  properties:
                    attributeName:
                      type: string
                    attributeType:
                      type: string
                  type: object
                type: array
              billingMode:
                type: string
              globalSecondaryIndexes:
                items:
                  properties:
                    indexName:
                      type: string
                    keySchema:
                      items:
                        properties:
                          attributeName:
                            type: string
                          keyType:
                            type: string
                        type: object
                      type: array
                    projection:
                      properties:
                        nonKeyAttributes:
                          items:
                            type: string
                          type: array
                        projectionType:
                          type: string
                      type: object
                    provisionedThroughput:
                      properties:
                        readCapacityUnits:
                          format: int64
                          type: integer
                        writeCapacityUnits:
                          format: int64
                          type: integer
                      type: object
                  type: object
                type: array
              keySchema:
                items:
                  properties:
                    attributeName:
                      type: string
                    keyType:
                      type: string
                  type: object
                type: array
              localSecondaryIndexes:
                items:
                  properties:
                    indexName:
                      type: string
                    keySchema:
                      items:
                        properties:
                          attributeName:
                            type: string
                          keyType:
                            type: string
                        type: object
                      type: array
                    projection:
                      properties:
                        nonKeyAttributes:
                          items:
                            type: string
                          type: array
                        projectionType:
                          type: string
                      type: object
                  type: object
                type: array
              provisionedThroughput:
                properties:
                  readCapacityUnits:
                    format: int64
                    type: integer
                  writeCapacityUnits:
                    format: int64
                    type: integer
                type: object
              sseSpecification:
                properties:
                  enabled:
                    type: boolean
                  kmsMasterKeyID:
                    type: string
                  sseType:
                    type: string
                type: object
              streamSpecification:
                properties:
                  streamEnabled:
                    type: boolean
                  streamViewType:
                    type: string
                type: object
              tableName:
                type: string
              tags:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
            required:
            - attributeDefinitions
            - keySchema
            - tableName
            type: object
          status:
            description: TableStatus defines the observed state of Table
            properties:
              ackResourceMetadata:
                description: All CRs managed by ACK have a common `Status.ACKResourceMetadata`
                  member that is used to contain resource sync state, account ownership,
                  constructed ARN for the resource
                properties:
                  arn:
                    description: 'ARN is the Amazon Resource Name for the resource.
                      This is a globally-unique identifier and is set only by the
                      ACK service controller once the controller has orchestrated
                      the creation of the resource OR when it has verified that an
                      "adopted" resource (a resource where the ARN annotation was
                      set by the Kubernetes user on the CR) exists and matches the
                      supplied CR''s Spec field values. TODO(vijat@): Find a better
                      strategy for resources that do not have ARN in CreateOutputResponse
                      https://github.com/aws/aws-controllers-k8s/issues/270'
                    type: string
                  ownerAccountID:
                    description: OwnerAccountID is the AWS Account ID of the account
                      that owns the backend AWS service API resource.
                    type: string
                required:
                - ownerAccountID
                type: object
              archivalSummary:
                properties:
                  archivalBackupARN:
                    type: string
                  archivalDateTime:
                    format: date-time
                    type: string
                  archivalReason:
                    type: string
                type: object
              billingModeSummary:
                properties:
                  billingMode:
                    type: string
                  lastUpdateToPayPerRequestDateTime:
                    format: date-time
                    type: string
                type: object
              conditions:
                description: All CRS managed by ACK have a common `Status.Conditions`
                  member that contains a collection of `ackv1alpha1.Condition` objects
                  that describe the various terminal states of the CR and its backend
                  AWS service API resource
                items:
                  description: Condition is the common struct used by all CRDs managed
                    by ACK service controllers to indicate terminal states  of the
                    CR and its backend AWS service API resource
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the Condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              creationDateTime:
                format: date-time
                type: string
              globalTableVersion:
                type: string
              itemCount:
                format: int64
                type: integer
              latestStreamARN:
                type: string
              latestStreamLabel:
                type: string
              replicas:
                items:
                  properties:
                    globalSecondaryIndexes:
                      items:
                        properties:
                          indexName:
                            type: string
                          provisionedThroughputOverride:
                            properties:
                              readCapacityUnits:
                                format: int64
                                type: integer
                            type: object
                        type: object
                      type: array
                    kmsMasterKeyID:
                      type: string
                    provisionedThroughputOverride:
                      properties:
                        readCapacityUnits:
                          format: int64
                          type: integer
                      type: object
                    regionName:
                      type: string
                    replicaStatus:
                      type: string
                    replicaStatusDescription:
                      type: string
                    replicaStatusPercentProgress:
                      type: string
                  type: object
                type: array
              restoreSummary:
                properties:
                  restoreDateTime:
                    format: date-time
                    type: string
                  restoreInProgress:
                    type: boolean
                  sourceBackupARN:
                    type: string
                  sourceTableARN:
                    type: string
                type: object
              sseDescription:
                properties:
                  inaccessibleEncryptionDateTime:
                    format: date-time
                    type: string
                  kmsMasterKeyARN:
                    type: string
                  sseType:
                    type: string
                  status:
                    type: string
                type: object
              tableID:
                type: string
              tableSizeBytes:
                format: int64
                type: integer
              tableStatus:
                type: string
            required:
            - ackResourceMetadata
            - conditions
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
