apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/elasticache.services.k8s.aws_cachesubnetgroups.yaml
  - bases/elasticache.services.k8s.aws_replicationgroups.yaml
  - bases/elasticache.services.k8s.aws_snapshots.yaml
