
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.1-0.20200716001835-4a903ddb7005
  creationTimestamp: null
  name: replicationgroups.elasticache.services.k8s.aws
spec:
  group: elasticache.services.k8s.aws
  names:
    kind: ReplicationGroup
    listKind: ReplicationGroupList
    plural: replicationgroups
    singular: replicationgroup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ReplicationGroup is the Schema for the ReplicationGroups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ReplicationGroupSpec defines the desired state of ReplicationGroup
          properties:
            atRestEncryptionEnabled:
              type: boolean
            authToken:
              type: string
            autoMinorVersionUpgrade:
              type: boolean
            automaticFailoverEnabled:
              type: boolean
            cacheNodeType:
              type: string
            cacheParameterGroupName:
              type: string
            cacheSecurityGroupNames:
              items:
                type: string
              type: array
            cacheSubnetGroupName:
              type: string
            engine:
              type: string
            engineVersion:
              type: string
            globalReplicationGroupID:
              type: string
            kmsKeyID:
              type: string
            multiAZEnabled:
              type: boolean
            nodeGroupConfiguration:
              items:
                properties:
                  nodeGroupID:
                    type: string
                  primaryAvailabilityZone:
                    type: string
                  replicaAvailabilityZones:
                    items:
                      type: string
                    type: array
                  replicaCount:
                    format: int64
                    type: integer
                  slots:
                    type: string
                type: object
              type: array
            notificationTopicARN:
              type: string
            numCacheClusters:
              format: int64
              type: integer
            numNodeGroups:
              format: int64
              type: integer
            port:
              format: int64
              type: integer
            preferredCacheClusterAZs:
              items:
                type: string
              type: array
            preferredMaintenanceWindow:
              type: string
            primaryClusterID:
              type: string
            replicasPerNodeGroup:
              format: int64
              type: integer
            replicationGroupDescription:
              type: string
            replicationGroupID:
              type: string
            securityGroupIDs:
              items:
                type: string
              type: array
            snapshotARNs:
              items:
                type: string
              type: array
            snapshotName:
              type: string
            snapshotRetentionLimit:
              format: int64
              type: integer
            snapshotWindow:
              type: string
            tags:
              items:
                properties:
                  key:
                    type: string
                  value:
                    type: string
                type: object
              type: array
            transitEncryptionEnabled:
              type: boolean
          type: object
        status:
          description: ReplicationGroupStatus defines the observed state of ReplicationGroup
          properties:
            ackResourceMetadata:
              description: All CRs managed by ACK have a common `Status.ACKResourceMetadata`
                member that is used to contain resource sync state, account ownership,
                constructed ARN for the resource
              properties:
                arn:
                  description: 'ARN is the Amazon Resource Name for the resource.
                    This is a globally-unique identifier and is set only by the ACK
                    service controller once the controller has orchestrated the creation
                    of the resource OR when it has verified that an "adopted" resource
                    (a resource where the ARN annotation was set by the Kubernetes
                    user on the CR) exists and matches the supplied CR''s Spec field
                    values. TODO(vijat@): Find a better strategy for resources that
                    do not have ARN in CreateOutputResponse https://github.com/aws/aws-controllers-k8s/issues/270'
                  type: string
                ownerAccountID:
                  description: OwnerAccountID is the AWS Account ID of the account
                    that owns the backend AWS service API resource.
                  type: string
              required:
              - ownerAccountID
              type: object
            authTokenEnabled:
              type: boolean
            authTokenLastModifiedDate:
              format: date-time
              type: string
            automaticFailover:
              type: string
            clusterEnabled:
              type: boolean
            conditions:
              description: All CRS managed by ACK have a common `Status.Conditions`
                member that contains a collection of `ackv1alpha1.Condition` objects
                that describe the various terminal states of the CR and its backend
                AWS service API resource
              items:
                description: Condition is the common struct used by all CRDs managed
                  by ACK service controllers to indicate terminal states  of the CR
                  and its backend AWS service API resource
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the Condition
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            configurationEndpoint:
              properties:
                address:
                  type: string
                port:
                  format: int64
                  type: integer
              type: object
            description:
              type: string
            globalReplicationGroupInfo:
              properties:
                globalReplicationGroupID:
                  type: string
                globalReplicationGroupMemberRole:
                  type: string
              type: object
            memberClusters:
              items:
                type: string
              type: array
            multiAZ:
              type: string
            nodeGroups:
              items:
                properties:
                  nodeGroupID:
                    type: string
                  nodeGroupMembers:
                    items:
                      properties:
                        cacheClusterID:
                          type: string
                        cacheNodeID:
                          type: string
                        currentRole:
                          type: string
                        preferredAvailabilityZone:
                          type: string
                        readEndpoint:
                          properties:
                            address:
                              type: string
                            port:
                              format: int64
                              type: integer
                          type: object
                      type: object
                    type: array
                  primaryEndpoint:
                    properties:
                      address:
                        type: string
                      port:
                        format: int64
                        type: integer
                    type: object
                  readerEndpoint:
                    properties:
                      address:
                        type: string
                      port:
                        format: int64
                        type: integer
                    type: object
                  slots:
                    type: string
                  status:
                    type: string
                type: object
              type: array
            pendingModifiedValues:
              properties:
                authTokenStatus:
                  type: string
                automaticFailoverStatus:
                  type: string
                primaryClusterID:
                  type: string
                resharding:
                  properties:
                    slotMigration:
                      properties:
                        progressPercentage:
                          type: number
                      type: object
                  type: object
              type: object
            snapshottingClusterID:
              type: string
            status:
              type: string
          required:
          - ackResourceMetadata
          - conditions
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
