name: e2e-test
on:
  # Allow manual trigger of e2e tests
  workflow_dispatch:

jobs:
  test-controllers:
    name: test controllers
    strategy:
      fail-fast: false
      matrix:
        service:
         - s3
         - ecr
         - sns
         - sqs
         - elasticache
         - dynamodb
         - apigatewayv2
         - sagemaker
    runs-on: [self-hosted, aws-controllers-k8s]
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      - name: checkout code
        uses: actions/checkout@v2
      - name: build ack-generate
        run: make build-ack-generate
      - name: build controller
        run: ./scripts/build-controller.sh $SERVICE
        env:
          SERVICE: ${{ matrix.service }}
      - name: execute e2e tests
        run: |
          export ACK_ROLE_ARN=$(aws ssm get-parameter --name ACK_ROLE_ARN | jq -r '.Parameter.Value')
          export ACK_ROLE_ARN_ALT=$(aws ssm get-parameter --name ACK_ROLE_ARN_ALT | jq -r '.Parameter.Value')
          ./scripts/kind-build-test.sh $SERVICE
        env:
          SERVICE: ${{ matrix.service }}
